/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UndanganTokenRouteImport } from './routes/undangan.$token'
import { Route as RsvpTokenRouteImport } from './routes/rsvp.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as CheckInTokenRouteImport } from './routes/check-in.$token'
import { Route as BlogCategoriesRouteImport } from './routes/blog/categories'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSeserahanRouteImport } from './routes/_authenticated/seserahan'
import { Route as AuthenticatedRundownRouteImport } from './routes/_authenticated/rundown'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedGuestsRouteImport } from './routes/_authenticated/guests'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommandCenterRouteImport } from './routes/_authenticated/command-center'
import { Route as AuthenticatedChecklistRouteImport } from './routes/_authenticated/checklist'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as BlogCategoriesSlugRouteImport } from './routes/blog/categories.$slug'
import { Route as ApiDocumentsSplatRouteImport } from './routes/api/documents/$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UndanganTokenRoute = UndanganTokenRouteImport.update({
  id: '/undangan/$token',
  path: '/undangan/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpTokenRoute = RsvpTokenRouteImport.update({
  id: '/rsvp/$token',
  path: '/rsvp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInTokenRoute = CheckInTokenRouteImport.update({
  id: '/check-in/$token',
  path: '/check-in/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoriesRoute = BlogCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeserahanRoute = AuthenticatedSeserahanRouteImport.update({
  id: '/seserahan',
  path: '/seserahan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRundownRoute = AuthenticatedRundownRouteImport.update({
  id: '/rundown',
  path: '/rundown',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuestsRoute = AuthenticatedGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandCenterRoute =
  AuthenticatedCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistRoute = AuthenticatedChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogCategoriesSlugRoute = BlogCategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogCategoriesRoute,
} as any)
const ApiDocumentsSplatRoute = ApiDocumentsSplatRouteImport.update({
  id: '/api/documents/$',
  path: '/api/documents/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/rundown': typeof AuthenticatedRundownRoute
  '/seserahan': typeof AuthenticatedSeserahanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/categories': typeof BlogCategoriesRouteWithChildren
  '/check-in/$token': typeof CheckInTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/undangan/$token': typeof UndanganTokenRoute
  '/api/documents/$': typeof ApiDocumentsSplatRoute
  '/blog/categories/$slug': typeof BlogCategoriesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/rundown': typeof AuthenticatedRundownRoute
  '/seserahan': typeof AuthenticatedSeserahanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/categories': typeof BlogCategoriesRouteWithChildren
  '/check-in/$token': typeof CheckInTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/undangan/$token': typeof UndanganTokenRoute
  '/api/documents/$': typeof ApiDocumentsSplatRoute
  '/blog/categories/$slug': typeof BlogCategoriesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/checklist': typeof AuthenticatedChecklistRoute
  '/_authenticated/command-center': typeof AuthenticatedCommandCenterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/guests': typeof AuthenticatedGuestsRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/rundown': typeof AuthenticatedRundownRoute
  '/_authenticated/seserahan': typeof AuthenticatedSeserahanRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/categories': typeof BlogCategoriesRouteWithChildren
  '/check-in/$token': typeof CheckInTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/undangan/$token': typeof UndanganTokenRoute
  '/api/documents/$': typeof ApiDocumentsSplatRoute
  '/blog/categories/$slug': typeof BlogCategoriesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/privacy'
    | '/terms'
    | '/budget'
    | '/checklist'
    | '/command-center'
    | '/dashboard'
    | '/documents'
    | '/guests'
    | '/notes'
    | '/rundown'
    | '/seserahan'
    | '/settings'
    | '/timeline'
    | '/vendors'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog/categories'
    | '/check-in/$token'
    | '/invite/$token'
    | '/rsvp/$token'
    | '/undangan/$token'
    | '/api/documents/$'
    | '/blog/categories/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/privacy'
    | '/terms'
    | '/budget'
    | '/checklist'
    | '/command-center'
    | '/dashboard'
    | '/documents'
    | '/guests'
    | '/notes'
    | '/rundown'
    | '/seserahan'
    | '/settings'
    | '/timeline'
    | '/vendors'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog/categories'
    | '/check-in/$token'
    | '/invite/$token'
    | '/rsvp/$token'
    | '/undangan/$token'
    | '/api/documents/$'
    | '/blog/categories/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/privacy'
    | '/terms'
    | '/_authenticated/budget'
    | '/_authenticated/checklist'
    | '/_authenticated/command-center'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/guests'
    | '/_authenticated/notes'
    | '/_authenticated/rundown'
    | '/_authenticated/seserahan'
    | '/_authenticated/settings'
    | '/_authenticated/timeline'
    | '/_authenticated/vendors'
    | '/auth_/callback'
    | '/blog/$slug'
    | '/blog/categories'
    | '/check-in/$token'
    | '/invite/$token'
    | '/rsvp/$token'
    | '/undangan/$token'
    | '/api/documents/$'
    | '/blog/categories/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CheckInTokenRoute: typeof CheckInTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
  RsvpTokenRoute: typeof RsvpTokenRoute
  UndanganTokenRoute: typeof UndanganTokenRoute
  ApiDocumentsSplatRoute: typeof ApiDocumentsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/undangan/$token': {
      id: '/undangan/$token'
      path: '/undangan/$token'
      fullPath: '/undangan/$token'
      preLoaderRoute: typeof UndanganTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp/$token': {
      id: '/rsvp/$token'
      path: '/rsvp/$token'
      fullPath: '/rsvp/$token'
      preLoaderRoute: typeof RsvpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in/$token': {
      id: '/check-in/$token'
      path: '/check-in/$token'
      fullPath: '/check-in/$token'
      preLoaderRoute: typeof CheckInTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/categories': {
      id: '/blog/categories'
      path: '/categories'
      fullPath: '/blog/categories'
      preLoaderRoute: typeof BlogCategoriesRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seserahan': {
      id: '/_authenticated/seserahan'
      path: '/seserahan'
      fullPath: '/seserahan'
      preLoaderRoute: typeof AuthenticatedSeserahanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rundown': {
      id: '/_authenticated/rundown'
      path: '/rundown'
      fullPath: '/rundown'
      preLoaderRoute: typeof AuthenticatedRundownRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guests': {
      id: '/_authenticated/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AuthenticatedGuestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-center': {
      id: '/_authenticated/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist': {
      id: '/_authenticated/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AuthenticatedChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/categories/$slug': {
      id: '/blog/categories/$slug'
      path: '/$slug'
      fullPath: '/blog/categories/$slug'
      preLoaderRoute: typeof BlogCategoriesSlugRouteImport
      parentRoute: typeof BlogCategoriesRoute
    }
    '/api/documents/$': {
      id: '/api/documents/$'
      path: '/api/documents/$'
      fullPath: '/api/documents/$'
      preLoaderRoute: typeof ApiDocumentsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedChecklistRoute: typeof AuthenticatedChecklistRoute
  AuthenticatedCommandCenterRoute: typeof AuthenticatedCommandCenterRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedGuestsRoute: typeof AuthenticatedGuestsRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedRundownRoute: typeof AuthenticatedRundownRoute
  AuthenticatedSeserahanRoute: typeof AuthenticatedSeserahanRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedChecklistRoute: AuthenticatedChecklistRoute,
  AuthenticatedCommandCenterRoute: AuthenticatedCommandCenterRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedGuestsRoute: AuthenticatedGuestsRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedRundownRoute: AuthenticatedRundownRoute,
  AuthenticatedSeserahanRoute: AuthenticatedSeserahanRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogCategoriesRouteChildren {
  BlogCategoriesSlugRoute: typeof BlogCategoriesSlugRoute
}

const BlogCategoriesRouteChildren: BlogCategoriesRouteChildren = {
  BlogCategoriesSlugRoute: BlogCategoriesSlugRoute,
}

const BlogCategoriesRouteWithChildren = BlogCategoriesRoute._addFileChildren(
  BlogCategoriesRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogCategoriesRoute: typeof BlogCategoriesRouteWithChildren
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogCategoriesRoute: BlogCategoriesRouteWithChildren,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CheckInTokenRoute: CheckInTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
  RsvpTokenRoute: RsvpTokenRoute,
  UndanganTokenRoute: UndanganTokenRoute,
  ApiDocumentsSplatRoute: ApiDocumentsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
