/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedGuestsRouteImport } from './routes/_authenticated/guests'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedChecklistRouteImport } from './routes/_authenticated/checklist'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/_authenticated/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/_authenticated/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/_authenticated/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGuestsRoute = AuthenticatedGuestsRouteImport.update({
  id: '/_authenticated/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/_authenticated/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChecklistRoute = AuthenticatedChecklistRouteImport.update({
  id: '/_authenticated/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/_authenticated/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/budget': typeof AuthenticatedBudgetRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/budget': typeof AuthenticatedBudgetRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/checklist': typeof AuthenticatedChecklistRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/guests': typeof AuthenticatedGuestsRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/budget'
    | '/checklist'
    | '/documents'
    | '/guests'
    | '/notes'
    | '/settings'
    | '/timeline'
    | '/vendors'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/budget'
    | '/checklist'
    | '/documents'
    | '/guests'
    | '/notes'
    | '/settings'
    | '/timeline'
    | '/vendors'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/budget'
    | '/_authenticated/checklist'
    | '/_authenticated/documents'
    | '/_authenticated/guests'
    | '/_authenticated/notes'
    | '/_authenticated/settings'
    | '/_authenticated/timeline'
    | '/_authenticated/vendors'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedChecklistRoute: typeof AuthenticatedChecklistRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedGuestsRoute: typeof AuthenticatedGuestsRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/guests': {
      id: '/_authenticated/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AuthenticatedGuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checklist': {
      id: '/_authenticated/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AuthenticatedChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedChecklistRoute: AuthenticatedChecklistRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedGuestsRoute: AuthenticatedGuestsRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
